Updated README.md and added mocha to run the existing test.
andywer/leakage pull request #1
Opened 2016-12-27 22:09 UTC by kroogs

When I imported 'iterate' from the package, the value was undefined. I realized that the README.md was misleading, so this PR adjusts it to reflect what the package exports ('iteration').

I'm having another issue with the library, which might end up in another PR, so I wanted to run the test suite to see what happens and realized that it didn't come with mocha and needed an improved test command (both using mocha and not relying on any local PATH modifications).

2016-12-27 22:27 UTC, btmills commented on README.md
> +import { iteration } from 'leakage'
Thanks for fixing this! It took me a moment to figure out why my import wasn't working before I discovered the name was different.

2016-12-27 22:27 UTC, btmills commented on package.json
> +    "test": "node_modules/.bin/standard lib/**/*.js && node_modules/.bin/mocha test"
npm adds `node_modules/.bin` to `PATH`, so you can use `standard` and `mocha` without the manual path prefix

2016-12-27 22:32 UTC, kroogs commented on package.json
> +    "test": "node_modules/.bin/standard lib/**/*.js && node_modules/.bin/mocha test"
Ah, I didn't know they added this. Thank you.

2016-12-27 22:33 UTC, btmills commented on package.json
> +    "test": "node_modules/.bin/standard lib/**/*.js && node_modules/.bin/mocha test"
:+1: Sure thing! Here's that section in the docs, in case you're interested in reading more: https://docs.npmjs.com/misc/scripts#path

2016-12-28 08:53 UTC, andywer commented
Ahhh, I'm sorry for the misleading docs, guys! Thanks for fixing, @kroogs!

2016-12-28 08:55 UTC, andywer requested changes
Just one thing: Now you run `mocha` on `npm test` (see) package.json. But the test in `test/` is supposed to fail, so `npm test` will always fail.

Let's skip the `package.json` modification for now. I will open a new PR introducing at least a little bit of unit/integration testing.

2016-12-28 09:49 UTC, andywer commented
@btmills @kroogs Do you prefer `iterate` or `iteration`?

2016-12-28 09:53 UTC, btmills commented
`iterate` feels more natural to me. And if you want to avoid a breaking change, you can rename it and change the docs, then do `module.exports = { iterate, iteration: iterate };`, while officially deprecating `iteration`.

2016-12-28 10:02 UTC, andywer commented
@btmills Yeah, feeling the same. I will just edit the PR.

2016-12-28 10:03 UTC, andywer commented
Or maybe not... Guess it's easier to start a new one, since editing so much isn't easy using the GitHub web UI.

2016-12-28 10:16 UTC, andywer commented
Opened a new PR. Still thankful that you opened this one, @kroogs :)

2016-12-28 10:16 UTC, closed without merging